[tool.black]
line-length = 120
target-version = ['py311']
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
  | .git
  | __pycache__
  | allure-results
  | allure-report
  | .pytest_cache
  | main.py
)/
'''

[tool.isort]
profile = "black"
line_length = 120
skip = [
    "venv",
    ".venv",
    "env",
    ".git",
    "__pycache__",
    "allure-results",
    "allure-report",
    ".pytest_cache",
]

[tool.pytest.ini_options]
testpaths = [
    "pageobject_structure/tests"
]
norecursedirs = [
    ".*", "venv", "env", "__pycache__", "Library", "Applications"
]
markers = [
    "only: marks tests to run only this test (deselect all others)"
]